on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion:
          - "5.2"
          - "5.3"
          - "5.4"
          - "luajit-2.1"
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v6
      - name: Install busted
        run: luarocks install busted
      - name: Run tests
        run: busted -p _test .
